-- MySQL Script generated by MySQL Workbench
-- 08/17/16 17:21:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema booksdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `booksdb` ;

-- -----------------------------------------------------
-- Schema booksdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booksdb` DEFAULT CHARACTER SET utf8 ;
USE `booksdb` ;

-- -----------------------------------------------------
-- Table `booksdb`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`author` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NULL,
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`field` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`field` (
  `field_id` INT NOT NULL AUTO_INCREMENT,
  `field_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`field_id`),
  UNIQUE INDEX `field_name_UNIQUE` (`field_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`language` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`language_id`),
  UNIQUE INDEX `language_name_UNIQUE` (`language_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`book` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `descreption` TEXT NULL,
  `year` SMALLINT(4) NULL,
  `ISBN` VARCHAR(45) NULL,
  `price` DECIMAL(6,2) NULL,
  `quantity` SMALLINT(4) NULL,
  `number_pages` SMALLINT(3) NULL,
  `cover` BLOB NULL,
  `field_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_book_field_idx` (`field_id` ASC),
  INDEX `fk_book_language1_idx` (`language_id` ASC),
  INDEX `fk_book_author1_idx` (`author_id` ASC),
  CONSTRAINT `fk_book_field`
    FOREIGN KEY (`field_id`)
    REFERENCES `booksdb`.`field` (`field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `booksdb`.`language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `booksdb`.`author` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`level` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`level` (
  `level_id` INT NOT NULL AUTO_INCREMENT,
  `level_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`level_id`),
  UNIQUE INDEX `level_name_UNIQUE` (`level_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`book_has_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`book_has_level` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`book_has_level` (
  `book_id` INT NOT NULL,
  `level_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `level_id`),
  INDEX `fk_book_has_level_level1_idx` (`level_id` ASC),
  INDEX `fk_book_has_level_book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_has_level_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `booksdb`.`book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_has_level_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `booksdb`.`level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
