-- MySQL Script generated by MySQL Workbench
-- 08/19/16 00:02:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema booksdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `booksdb` ;

-- -----------------------------------------------------
-- Schema booksdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booksdb` DEFAULT CHARACTER SET utf8 ;
USE `booksdb` ;


-- -----------------------------------------------------
-- Table `booksdb`.`keys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`keys`;

CREATE TABLE `keys` (
   `id` INT(11) NOT NULL AUTO_INCREMENT,
   `user_id` INT(11) NOT NULL,
   `key` VARCHAR(40) NOT NULL,
   `level` INT(2) NOT NULL,
   `ignore_limits` TINYINT(1) NOT NULL DEFAULT '0',
   `is_private_key` TINYINT(1)  NOT NULL DEFAULT '0',
   `ip_addresses` TEXT NULL DEFAULT NULL,
   `date_created` INT(11) NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- -----------------------------------------------------
-- Table `booksdb`.`logs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`logs`;

CREATE TABLE `logs` (
   `id` INT(11) NOT NULL AUTO_INCREMENT,
   `uri` VARCHAR(255) NOT NULL,
   `method` VARCHAR(6) NOT NULL,
   `params` TEXT DEFAULT NULL,
   `api_key` VARCHAR(40) NOT NULL,
   `ip_address` VARCHAR(45) NOT NULL,
   `time` INT(11) NOT NULL,
   `rtime` FLOAT DEFAULT NULL,
   `authorized` VARCHAR(1) NOT NULL,
   `response_code` SMALLINT(3) DEFAULT '0',
   PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


-- -----------------------------------------------------
-- Table `booksdb`.`author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`author` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`author` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NULL,
  `ip_address` VARCHAR(45) NULL,
  `author_status` ENUM('active', 'deleted') NOT NULL DEFAULT 'active',
  PRIMARY KEY (`author_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`field` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`field` (
  `field_id` INT NOT NULL AUTO_INCREMENT,
  `field_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`field_id`),
  UNIQUE INDEX `field_name_UNIQUE` (`field_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`language` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`language` (
  `language_id` INT NOT NULL AUTO_INCREMENT,
  `language_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`language_id`),
  UNIQUE INDEX `language_name_UNIQUE` (`language_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`book` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`book` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `descreption` TEXT NULL,
  `year` SMALLINT(4) NULL,
  `ISBN` VARCHAR(45) NULL,
  `price` DECIMAL(6,2) NULL,
  `quantity` SMALLINT(4) NULL,
  `number_pages` SMALLINT(3) NULL,
  `cover` BLOB NULL,
  `field_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`book_id`),
  INDEX `fk_book_field_idx` (`field_id` ASC),
  INDEX `fk_book_language1_idx` (`language_id` ASC),
  CONSTRAINT `fk_book_field`
    FOREIGN KEY (`field_id`)
    REFERENCES `booksdb`.`field` (`field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `booksdb`.`language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`level` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`level` (
  `level_id` INT NOT NULL AUTO_INCREMENT,
  `level_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`level_id`),
  UNIQUE INDEX `level_name_UNIQUE` (`level_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`book_has_level`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`book_has_level` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`book_has_level` (
  `book_id` INT NOT NULL,
  `level_id` INT NOT NULL,
  PRIMARY KEY (`book_id`, `level_id`),
  INDEX `fk_book_has_level_level1_idx` (`level_id` ASC),
  INDEX `fk_book_has_level_book1_idx` (`book_id` ASC),
  CONSTRAINT `fk_book_has_level_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `booksdb`.`book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_book_has_level_level1`
    FOREIGN KEY (`level_id`)
    REFERENCES `booksdb`.`level` (`level_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booksdb`.`author_has_book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booksdb`.`author_has_book` ;

CREATE TABLE IF NOT EXISTS `booksdb`.`author_has_book` (
  `author_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  PRIMARY KEY (`author_id`, `book_id`),
  INDEX `fk_author_has_book_book1_idx` (`book_id` ASC),
  INDEX `fk_author_has_book_author1_idx` (`author_id` ASC),
  CONSTRAINT `fk_author_has_book_author1`
    FOREIGN KEY (`author_id`)
    REFERENCES `booksdb`.`author` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_author_has_book_book1`
    FOREIGN KEY (`book_id`)
    REFERENCES `booksdb`.`book` (`book_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
